FROM python:3.12-slim

WORKDIR /app

COPY userExtractor9000.py .
COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh

RUN pip install psycopg2-binary

ENTRYPOINT ["./wait-for-it.sh", "database:5432", "-t", "15", "--", "python", "userExtractor9000.py"] 