services:
  webserver:
    image: nginx
    container_name: webserver
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/includes/:/etc/nginx/includes/
      - ./webserver/html:/usr/share/nginx/html/
    ports:
      - 80:80
    networks:
      acad-net:

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: moi
      KEYCLOAK_ADMIN_PASSWORD: moi
      # CA SERT A RIEN TOUT CA AHAHAHAHAHHAHAHAHAHAHAHHAHAHAHAHHA CEST TROP DROLE AHAHAH

#      KC_HOSTNAME_STRICT: "false"
#      KC_HOSTNAME_STRICT_HTTPS: "false"
#      KC_HTTP_ENABLED: "true"
#      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_SUCCESS_LEVEL: "info"
#      KC_HOSTNAME: "localhost"
#      KC_SPI_CORS_DEFAULT_ALLOWED_ORIGINS: "http://localhost:80,http://localhost:8080,http://localhost,*"
#      KC_SPI_CORS_DEFAULT_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
#      KC_SPI_CORS_DEFAULT_ALLOWED_HEADERS: "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization"
#      KC_SPI_CORS_DEFAULT_EXPOSED_HEADERS: "Location,Content-Disposition"
#      KC_SPI_CORS_DEFAULT_ALLOW_CREDENTIALS: "true"
    ports:
      - "6969:8080"
    command: start-dev  --import-realm
    networks:
      acad-net: #nettest:
    volumes:
      - keycloak_data:/opt/keycloak/data

  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5444:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laplacebazardDB #bazar avec un 'd' de plus? -zak
    networks:
      acad-net:

networks:
  acad-net:

volumes:
    keycloak_data: