services:
  webserver:
    image: nginx
    container_name: webserver
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/includes/:/etc/nginx/includes/
      - ./webserver/html:/usr/share/nginx/html/
    ports:
      - 80:80
    networks:
      acad-net:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: moi
      KC_BOOTSTRAP_ADMIN_PASSWORD: moi

      KC_SPI_CORS_DEFAULT_ALLOWED_ORIGINS: "http://localhost,http://localhost:80,http://localhost:8080"
      KC_SPI_CORS_DEFAULT_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      KC_SPI_CORS_DEFAULT_ALLOWED_HEADERS: "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization"
      KC_SPI_CORS_DEFAULT_EXPOSED_HEADERS: "Location,Content-Disposition"
      KC_SPI_CORS_DEFAULT_ALLOW_CREDENTIALS: "true"

    ports:
      - "6969:8080"
    command: start-dev  --import-realm
    networks:
      acad-net: #nettest:
    volumes:
      - ./data/import:/opt/keycloak/data/import
    depends_on:
      - database
      - user-extractor

  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5444:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- laplace:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laplacebazarDB
    networks:
      acad-net:

  user-extractor:
    build:
      context: ./python
      dockerfile: Dockerfile.user-extractor
    volumes:
      - ./data/import:/app/docker/data/import
      - ./data:/app/docker/data
    networks:
      - acad-net
    restart: no
    depends_on:
      - database

networks:
  acad-net:

volumes:
    keycloak_data:
    #laplace: